import React, { useEffect } from 'react'
import Head from 'next/head'
import styled from 'styled-components'

const Main = styled.main`
  background-color: #1C1E11;
  color: #fff;
  width: 100vw;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  overflow-y: scroll;
  gap: 3rem;
`

const Title = styled.h1`
  font-size: 2rem;
  text-align: center;
  color: #DB0908;
  letter-spacing: 1px;
  text-transform: lowercase;
`;

const Form = styled.form`
  background: #fff;
  margin: 10px auto;
  padding: 15px;
  width: 80vw;
  border-radius: 10px;
  display: grid;
  justify-content: center;
  align-items: center;
`

const Field = styled.input`
  border: none;
  border-radius: 5px;
  height: 1.8rem;
  outline: none;
  width: 100%;
`

const TextArea = styled.textarea`
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 5px;
  height: 10rem;
  width: 60vw;
  outline: none;
`

const ContainerInput = styled.div`
  display: flex;
  flex-direction: column;
  margin: 10px 0;
  width: 60%;
`;

const Label = styled.label`
  color: #1C1E11;
  font-size: .9rem;
  margin: 8px 0 2px 0;
  font-weight: 700;
  letter-spacing: 1px;
  line-height: 1.8;
`

const Button = styled.button`
  width: 50%;
  height: 2rem;
  background: #DB0908;
  color: white;
  font-weight: 700;
  border-radius: 15px;
  border: none;
  cursor: pointer;
  letter-spacing: 1px;
  line-height: 1.8;
  justify-self: center;
  :hover {
    background: #C24747;
    transition: 0.3s ease;
    letter-spacing: 2px;
  }
`

const Span = styled.span`
  color: white;
  font-size: 1.5rem;
  letter-spacing: 1px;
  margin: 15px;
`

const Input = ({ id, value, label, action }) => {
  return (
    <ContainerInput>
      <Label id={id}>{label}</Label>
      <Field id={id} required type="text" value={value} onChange={action} />
      <div className="underline" />
    </ContainerInput>
  )
}

export default function Home() {

  const [name, setName] = React.useState('');
  const [tia, setTIA] = React.useState('');
  const [curso, setCurso] = React.useState('');
  const [semestre, setSemestre] = React.useState('');

  const textoMensagem = `
  Nome: ${name}

  PAD (Portal de Atendimento Discente) - Antigo TIA: ${tia}

  Curso: ${curso}

  Semestre: ${semestre}
  Eu apoio a candidatura de: Wesley Coutinho da Silva e Tainã Ribeiro Dias para o CONSU, para ocupar as posições de representante discente no CONSU e suplente, respectivamente.
`

  const [mensagem, setMensagem] = React.useState(textoMensagem);

  const submit = () => {
    window.open(`mailto:wesleycoutinho360@gmail.com,31989233@mackenzista.com.br?subject=ELEIÇÕES CONSU 2022&body=${mensagem}`);
  }

  useEffect(() => {
    setMensagem(textoMensagem);
  }, [textoMensagem]);

  return (
    <>
      <Head>
        <title>Consu - 4 da Manhã</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Main>
        <Title>
          O Quatro da Manhã no CONSU
        </Title>

        <Span>
          Apoie as candidaturas do Coletivo Quatro da Manhã ao CONSU 2022.
        </Span>

        <Form>

          <Input id="name" value={name} label="Nome" action={(e) => setName(e.target.value)} />
          <Input id="tia" value={tia} label="TIA" action={(e) => setTIA(e.target.value)} />
          <Input id="name" value={curso} label="Curso" action={(e) => setCurso(e.target.value)} />
          <Input id="sem" value={semestre} label="Semestre" action={(e) => setSemestre(e.target.value)} />

          <ContainerInput>
            <Label id="name">Mensagem</Label>
            <TextArea type="text" value={mensagem} onChange={(e) => setMensagem(e.target.value)} />
          </ContainerInput>
          <Button onClick={() => submit()}>Enviar</Button>
        </Form>
      </Main>
    </>
  )
}
